#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

set -o errexit -o nounset -o pipefail
trap 'echo "Error on line ${LINENO} of ${0}"; exit 1' ERR

if [[ -z "${ATC_COMPONENT:-}" ]]; then
	echo 'Missing environment variable ATC_COMPONENT' >&2
	exit 1
fi

TC_DIR="${GITHUB_WORKSPACE:-$(pwd)}"
cd "${TC_DIR}"

if [[ ! -f VERSION ]]; then
	echo "VERSION file not found in ${TC_DIR}" >&2
	exit 1
fi

TC_VERSION="$(<VERSION)"
PACKAGE_OS_VERSION="${PACKAGE_OS_VERSION:-ubuntu24.04}"
DIST_DIR="${TC_DIR}/dist"
SIMPLE="${SIMPLE:-0}"

mkdir -p "${DIST_DIR}"

APT_UPDATED=0
apt_update_if_needed() {
	if [[ "${APT_UPDATED}" -eq 0 ]]; then
		sudo apt-get update
		APT_UPDATED=1
	fi
}

ensure_cmd() {
	local cmd="$1"
	local pkg="$2"
	if ! command -v "${cmd}" >/dev/null 2>&1; then
		apt_update_if_needed
		sudo apt-get install -y --no-install-recommends "${pkg}"
	fi
}

install_npm_tool_if_missing() {
	local binary="$1"
	local package="$2"
	if command -v "${binary}" >/dev/null 2>&1; then
		return
	fi
	sudo npm install --global --force "${package}"
}

build_number() {
	local commits sha
	if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
		if ! commits="$(git describe --long --tags \
			--match='RELEASE-[0-9].[0-9].[0-9]' \
			--match='RELEASE-[0-9][0-9].[0-9][0-9].[0-9][0-9]' \
			--match='v[0-9].[0-9].[0-9]' \
			--match='v[0-9][0-9].[0-9][0-9].[0-9][0-9]' 2>/dev/null |
			awk -F- '{print $(NF-1)}')"; then
			commits=0
		fi
		sha="$(git rev-parse --short=8 HEAD)"
		echo "${commits}.${sha}"
		return
	fi

	if [[ -f BUILD_NUMBER ]]; then
		grep -v '^#' BUILD_NUMBER | head -n 1
		return
	fi

	echo "0.unknown"
}

BUILD_NUMBER="$(build_number)"
DEB_ARCH="$(dpkg --print-architecture 2>/dev/null || true)"
if [[ -z "${DEB_ARCH}" ]]; then
	case "$(uname -m)" in
		x86_64) DEB_ARCH='amd64' ;;
		aarch64|arm64) DEB_ARCH='arm64' ;;
		*) DEB_ARCH='amd64' ;;
	esac
fi

DEFAULT_DEB_VERSION="${TC_VERSION}-${BUILD_NUMBER}.${PACKAGE_OS_VERSION}"

pkg_output_name() {
	local pkg="$1"
	local ver="$2"
	local arch="$3"
	if [[ "${SIMPLE}" -eq 1 ]]; then
		echo "${pkg}.deb"
	else
		echo "${pkg}_${ver}_${arch}.deb"
	fi
}

create_deb() {
	local pkg="$1"
	local ver="$2"
	local arch="$3"
	local desc="$4"
	local depends="$5"
	local root="$6"
	local deb_pkg

	local debian_dir="${root}/DEBIAN"
	mkdir -p "${debian_dir}"
	# Debian package names cannot contain underscores; keep artifact filenames unchanged.
	deb_pkg="${pkg//_/-}"

	cat > "${debian_dir}/control" <<CONTROL
Package: ${deb_pkg}
Version: ${ver}
Section: misc
Priority: optional
Architecture: ${arch}
Maintainer: Apache Traffic Control <dev@trafficcontrol.apache.org>
Description: ${desc}
CONTROL

	if [[ -n "${depends}" ]]; then
		echo "Depends: ${depends}" >> "${debian_dir}/control"
	fi

	local outfile
	outfile="$(pkg_output_name "${pkg}" "${ver}" "${arch}")"
	dpkg-deb --root-owner-group --build "${root}" "${DIST_DIR}/${outfile}" >/dev/null
	echo "Built ${DIST_DIR}/${outfile}"
}

build_manpage() {
	local app="$1"
	local app_dir="$2"
	local desc="$3"
	local out_file="${app_dir}/${app}.1"
	local pandoc_version

	pandoc_version="$(pandoc --version | head -n1 | cut -d ' ' -f2)"
	{
		printf '%s %s\n' '.\\" Automatically generated by Pandoc' "${pandoc_version}"
		printf '%s\n' '.\\"'
		printf '.TH "%s" "1" "%s" "%s %s" "%s"\n' "${app}" "$(date '+%Y-%m-%d')" "${app}" "${TC_VERSION}" "${desc}"
		printf '%s\n' '.hy'
	} > "${out_file}"
	pandoc --strip-comments --to man "${app_dir}/README.md" >> "${out_file}"
}

build_cache_config_deb() {
	ensure_cmd go golang-go
	ensure_cmd rsync rsync
	ensure_cmd pandoc pandoc

	local cc_dir="${TC_DIR}/cache-config"
	local apps=(
		t3c
		t3c-apply
		t3c-generate
		t3c-request
		t3c-update
		t3c-check
		t3c-check-refs
		t3c-check-reload
		t3c-diff
		t3c-tail
		t3c-preprocess
	)

	(
		cd "${cc_dir}"
		go mod vendor -v

		local gcflags=''
		local ldflags='-s -w'
		export CGO_ENABLED=0

		for app in "${apps[@]}"; do
			(
				cd "${app}"
				go build -v -gcflags "${gcflags}" -ldflags "${ldflags} -X main.GitRevision=$(git -C "${TC_DIR}" rev-parse HEAD) -X main.BuildTimestamp=$(date +'%Y-%m-%dT%H:%M:%S') -X main.Version=${TC_VERSION}"
			)
			build_manpage "${app}" "${cc_dir}/${app}" 'ATC t3c Manual'
		done
	)

	local stage
	stage="$(mktemp -d)"
	local root="${stage}/root"
	mkdir -p "${root}/usr/bin" "${root}/usr/share/man/man1" "${root}/etc/logrotate.d" "${root}/var/log/trafficcontrol-cache-config" "${root}/var/lib/trafficcontrol-cache-config"

	for app in "${apps[@]}"; do
		install -m 0755 "${cc_dir}/${app}/${app}" "${root}/usr/bin/${app}"
		gzip -c -9 "${cc_dir}/${app}/${app}.1" > "${root}/usr/share/man/man1/${app}.1.gz"
	done

	install -m 0644 "${cc_dir}/build/atstccfg.logrotate" "${root}/etc/logrotate.d/atstccfg"
	touch "${root}/var/log/trafficcontrol-cache-config/atstccfg.log"

	create_deb 'trafficcontrol-cache-config' "${DEFAULT_DEB_VERSION}" "${DEB_ARCH}" 'Traffic Control cache configuration tools' 'git' "${root}"
}

build_tc_health_client_deb() {
	ensure_cmd go golang-go
	ensure_cmd pandoc pandoc

	local hc_dir="${TC_DIR}/tc-health-client"
	local logrotate_src="${hc_dir}/build/tc-health-client.logrotate"
	(
		cd "${hc_dir}"
		go mod vendor -v
		export CGO_ENABLED=0
		go build -v -ldflags "-s -w -X main.BuildTimestamp=$(date +'%Y-%m-%dT%H:%M:%S') -X main.Version=${TC_VERSION}-${BUILD_NUMBER}"
		pandoc --standalone --to man README.md -o tc-health-client.1
	)
	if [[ ! -f "${logrotate_src}" ]]; then
		logrotate_src="${hc_dir}/tc-health-client.logrotate"
	fi
	if [[ ! -f "${logrotate_src}" ]]; then
		echo "Missing tc-health-client logrotate file" >&2
		exit 1
	fi

	local stage
	stage="$(mktemp -d)"
	local root="${stage}/root"
	mkdir -p "${root}/usr/bin" "${root}/usr/share/man/man1" "${root}/etc/trafficcontrol" "${root}/etc/logrotate.d" "${root}/usr/lib/systemd/system"

	install -m 0755 "${hc_dir}/tc-health-client" "${root}/usr/bin/tc-health-client"
	gzip -c -9 "${hc_dir}/tc-health-client.1" > "${root}/usr/share/man/man1/tc-health-client.1.gz"
	install -m 0644 "${hc_dir}/tc-health-client.json" "${root}/etc/trafficcontrol/tc-health-client.sample.json"
	install -m 0644 "${logrotate_src}" "${root}/etc/logrotate.d/tc-health-client.logrotate"
	install -m 0644 "${hc_dir}/tc-health-client.service" "${root}/usr/lib/systemd/system/tc-health-client.service"

	create_deb 'trafficcontrol-health-client' "${DEFAULT_DEB_VERSION}" "${DEB_ARCH}" 'Traffic Control health client' '' "${root}"
}

build_traffic_monitor_deb() {
	ensure_cmd go golang-go
	ensure_cmd rsync rsync

	local tm_dir="${TC_DIR}/traffic_monitor"
	(
		cd "${tm_dir}"
		go mod vendor -v
		export CGO_ENABLED=0
		go build -v -ldflags "-s -w -X main.GitRevision=$(git -C "${TC_DIR}" rev-parse HEAD) -X main.BuildTimestamp=$(date +'%Y-%m-%dT%H:%M:%S') -X main.Version=${TC_VERSION}"
	)

	local stage
	stage="$(mktemp -d)"
	local root="${stage}/root"
	mkdir -p "${root}/opt/traffic_monitor/bin" "${root}/opt/traffic_monitor/conf" "${root}/opt/traffic_monitor/backup" "${root}/opt/traffic_monitor/static" "${root}/opt/traffic_monitor/var/run" "${root}/var/log/traffic_monitor" "${root}/etc/init.d" "${root}/etc/logrotate.d"

	install -m 0755 "${tm_dir}/traffic_monitor" "${root}/opt/traffic_monitor/bin/traffic_monitor"
	install -m 0644 "${tm_dir}/static/index.html" "${root}/opt/traffic_monitor/static/index.html"
	install -m 0644 "${tm_dir}/static/script.js" "${root}/opt/traffic_monitor/static/script.js"
	install -m 0644 "${tm_dir}/static/style.css" "${root}/opt/traffic_monitor/static/style.css"
	install -m 0644 "${tm_dir}/conf/traffic_ops.cfg" "${root}/opt/traffic_monitor/conf/traffic_ops.cfg"
	install -m 0644 "${tm_dir}/conf/traffic_monitor.cfg" "${root}/opt/traffic_monitor/conf/traffic_monitor.cfg"
	install -m 0755 "${tm_dir}/build/traffic_monitor.init" "${root}/etc/init.d/traffic_monitor"
	install -m 0644 "${tm_dir}/build/traffic_monitor.logrotate" "${root}/etc/logrotate.d/traffic_monitor"
	mkdir -p "${root}/opt/traffic_monitor/var"
	ln -s /var/log/traffic_monitor "${root}/opt/traffic_monitor/var/log"

	create_deb 'traffic_monitor' "${DEFAULT_DEB_VERSION}" "${DEB_ARCH}" 'Traffic Monitor' '' "${root}"
}

build_traffic_ops_deb() {
	ensure_cmd go golang-go
	ensure_cmd rsync rsync

	local to_dir="${TC_DIR}/traffic_ops"
	(
		cd "${to_dir}"
		go mod vendor -v
		export CGO_ENABLED=0
		(
			cd traffic_ops_golang
			go build -v -ldflags "-s -w -X main.version=traffic_ops-${TC_VERSION}-${BUILD_NUMBER}.${PACKAGE_OS_VERSION} -B 0x$(git -C "${TC_DIR}" rev-parse HEAD)"
		)
		(
			cd app/db
			go build -v -o admin -ldflags '-s -w'
		)
		(
			cd app/bin/checks/DnssecRefresh
			go build -v -o ToDnssecRefresh -ldflags '-s -w'
		)
		(
			cd app/db/reencrypt
			go build -v -o reencrypt
		)
		(
			cd app/db/traffic_vault_migrate
			go build -v -o traffic_vault_migrate
		)
		(
			cd install/bin/convert_profile
			go build -v -ldflags '-s -w'
		)
	)

	local stage
	stage="$(mktemp -d)"
	local root="${stage}/root"
	mkdir -p "${root}/opt/traffic_ops" "${root}/var/www/files" "${root}/var/log/traffic_ops"

	rsync -a "${to_dir}/etc" "${to_dir}/install" "${root}/opt/traffic_ops/"
	mkdir -p "${root}/opt/traffic_ops/app"
	rsync -a "${to_dir}/app/bin" "${to_dir}/app/conf" "${to_dir}/app/db" "${to_dir}/app/script" "${to_dir}/app/templates" "${root}/opt/traffic_ops/app/"

	install -m 0755 "${to_dir}/traffic_ops_golang/traffic_ops_golang" "${root}/opt/traffic_ops/app/bin/traffic_ops_golang"
	install -m 0755 "${to_dir}/app/db/admin" "${root}/opt/traffic_ops/app/db/admin"
	install -m 0755 "${to_dir}/app/bin/checks/DnssecRefresh/ToDnssecRefresh" "${root}/opt/traffic_ops/app/bin/checks/DnssecRefresh/ToDnssecRefresh"
	install -m 0755 "${to_dir}/app/db/reencrypt/reencrypt" "${root}/opt/traffic_ops/app/db/reencrypt/reencrypt"
	install -m 0755 "${to_dir}/app/db/traffic_vault_migrate/traffic_vault_migrate" "${root}/opt/traffic_ops/app/db/traffic_vault_migrate/traffic_vault_migrate"
	install -m 0755 "${to_dir}/install/bin/convert_profile/convert_profile" "${root}/opt/traffic_ops/install/bin/convert_profile/convert_profile"

	rm -f "${root}/opt/traffic_ops/app/db"/*.go || true
	rm -rf "${root}/opt/traffic_ops/app/db/trafficvault/test" || true
	rm -f "${root}/opt/traffic_ops/app/bin/checks/DnssecRefresh"/*.go || true
	rm -rf "${root}/opt/traffic_ops/app/bin/checks/DnssecRefresh/config" || true
	rm -f "${root}/opt/traffic_ops/app/db/reencrypt"/*.go || true
	rm -f "${root}/opt/traffic_ops/app/db/traffic_vault_migrate"/*.go || true
	rm -f "${root}/opt/traffic_ops/install/bin/convert_profile"/*.go || true

	install -m 0644 "${to_dir}/install/data/json/osversions.json" "${root}/var/www/files/osversions.json"

	create_deb 'traffic_ops' "${DEFAULT_DEB_VERSION}" "${DEB_ARCH}" 'Traffic Ops' '' "${root}"
}

build_traffic_portal_deb() {
	ensure_cmd npm npm
	ensure_cmd rsync rsync
	install_npm_tool_if_missing grunt grunt-cli
	install_npm_tool_if_missing sass sass

	local tp_dir="${TC_DIR}/traffic_portal"
	(
		cd "${tp_dir}"
		npm install
		npx grunt dist
		cd app/dist
		npm install --omit-dev
	)

	local stage
	stage="$(mktemp -d)"
	local root="${stage}/root"
	mkdir -p "${root}/etc/init.d" "${root}/etc/logrotate.d" "${root}/etc/traffic_portal" "${root}/opt/traffic_portal" "${root}/var/log/traffic_portal"

	install -m 0644 "${tp_dir}/server.js" "${root}/opt/traffic_portal/server.js"
	rsync -a "${tp_dir}/conf/" "${root}/etc/traffic_portal/conf/"
	rm -f "${root}/etc/traffic_portal/conf/configDev.js"
	install -m 0755 "${tp_dir}/build/etc/init.d/traffic_portal" "${root}/etc/init.d/traffic_portal"
	install -m 0644 "${tp_dir}/build/etc/logrotate.d/traffic_portal" "${root}/etc/logrotate.d/traffic_portal"
	install -m 0644 "${tp_dir}/build/etc/logrotate.d/traffic_portal-access" "${root}/etc/logrotate.d/traffic_portal-access"
	rsync -a "${tp_dir}/app/dist/" "${root}/opt/traffic_portal/"
	rm -f "${root}/opt/traffic_portal/package-lock.json"

	cat > "${root}/opt/traffic_portal/public/traffic_portal_release.json" <<RELEASE
{
"Version":"${TC_VERSION}-${BUILD_NUMBER}",
"Build Date":"$(date +'%Y-%m-%d %H:%M')"
}
RELEASE

	create_deb 'traffic_portal' "${DEFAULT_DEB_VERSION}" "${DEB_ARCH}" 'Traffic Portal' 'nodejs' "${root}"
}

build_traffic_portal_v2_deb() {
	ensure_cmd npm npm
	ensure_cmd rsync rsync

	local tp2_dir="${TC_DIR}/experimental/traffic-portal"
	(
		cd "${tp2_dir}"
		npm ci
		npx ng build --configuration production
	)

	local stage
	stage="$(mktemp -d)"
	local root="${stage}/root"
	mkdir -p "${root}/opt/traffic_portal_v2"
	rsync -a "${tp2_dir}/dist/traffic-portal/" "${root}/opt/traffic_portal_v2/"

	create_deb 'traffic_portal_v2' "${DEFAULT_DEB_VERSION}" "${DEB_ARCH}" 'Traffic Portal v2 assets' '' "${root}"
}

build_traffic_stats_deb() {
	ensure_cmd go golang-go
	ensure_cmd npm npm
	ensure_cmd rsync rsync

	local ts_dir="${TC_DIR}/traffic_stats"
	(
		cd "${ts_dir}"
		go mod vendor -v
		export CGO_ENABLED=0
		go build -v -ldflags '-s -w'
		(
			cd influxdb_tools
			go build -v -ldflags '-s -w' sync/sync_ts_databases.go
			go build -v -ldflags '-s -w' create/create_ts_databases.go
		)
		(
			cd trafficcontrol-scenes
			npm i --omit=dev
			npm run build
		)
	)

	local stage
	stage="$(mktemp -d)"
	local root="${stage}/root"
	mkdir -p "${root}/opt/traffic_stats/bin" "${root}/opt/traffic_stats/conf" "${root}/opt/traffic_stats/backup" "${root}/opt/traffic_stats/influxdb_tools" "${root}/opt/traffic_stats/var/run" "${root}/etc/init.d" "${root}/etc/logrotate.d" "${root}/var/log/traffic_stats" "${root}/var/lib/grafana/plugins/trafficcontrol-scenes-app"

	install -m 0755 "${ts_dir}/traffic_stats" "${root}/opt/traffic_stats/bin/traffic_stats"
	install -m 0644 "${ts_dir}/traffic_stats.cfg" "${root}/opt/traffic_stats/conf/traffic_stats.cfg"
	install -m 0644 "${ts_dir}/traffic_stats_seelog.xml" "${root}/opt/traffic_stats/conf/traffic_stats_seelog.xml"
	install -m 0755 "${ts_dir}/influxdb_tools/sync_ts_databases" "${root}/opt/traffic_stats/influxdb_tools/sync_ts_databases"
	install -m 0755 "${ts_dir}/influxdb_tools/create_ts_databases" "${root}/opt/traffic_stats/influxdb_tools/create_ts_databases"
	install -m 0755 "${ts_dir}/traffic_stats.init" "${root}/etc/init.d/traffic_stats"
	install -m 0644 "${ts_dir}/traffic_stats.logrotate" "${root}/etc/logrotate.d/traffic_stats"
	rsync -a "${ts_dir}/trafficcontrol-scenes/dist/" "${root}/var/lib/grafana/plugins/trafficcontrol-scenes-app/"
	mkdir -p "${root}/opt/traffic_stats/var"
	ln -s /var/log/traffic_stats "${root}/opt/traffic_stats/var/log"

	create_deb 'traffic_stats' "${DEFAULT_DEB_VERSION}" "${DEB_ARCH}" 'Traffic Stats' '' "${root}"
}

build_grove_deb() {
	ensure_cmd go golang-go
	local grove_dir="${TC_DIR}/grove"
	local grove_version
	grove_version="$(<"${grove_dir}/VERSION")"
	(
		cd "${grove_dir}"
		go mod vendor -v
		export CGO_ENABLED=0
		go build -v -ldflags "-s -w -X main.Version=${grove_version}"
	)

	local stage
	stage="$(mktemp -d)"
	local root="${stage}/root"
	mkdir -p "${root}/usr/sbin" "${root}/etc/grove" "${root}/var/log/grove" "${root}/etc/init.d" "${root}/etc/logrotate.d"
	install -m 0755 "${grove_dir}/grove" "${root}/usr/sbin/grove"
	install -m 0644 "${grove_dir}/conf/grove.cfg" "${root}/etc/grove/grove.cfg"
	install -m 0755 "${grove_dir}/build/grove.init" "${root}/etc/init.d/grove"
	install -m 0644 "${grove_dir}/build/grove.logrotate" "${root}/etc/logrotate.d/grove"
	create_deb 'grove' "${grove_version}-${BUILD_NUMBER}.${PACKAGE_OS_VERSION}" "${DEB_ARCH}" 'Grove caching proxy' '' "${root}"
}

build_grovetccfg_deb() {
	ensure_cmd go golang-go
	local gtc_dir="${TC_DIR}/grove/grovetccfg"
	local grove_version
	grove_version="$(<"${TC_DIR}/grove/VERSION")"
	(
		cd "${gtc_dir}"
		go mod vendor -v
		export CGO_ENABLED=0
		go build -v -ldflags "-s -w -X main.Version=${grove_version}"
	)

	local stage
	stage="$(mktemp -d)"
	local root="${stage}/root"
	mkdir -p "${root}/usr/sbin"
	install -m 0755 "${gtc_dir}/grovetccfg" "${root}/usr/sbin/grovetccfg"
	create_deb 'grovetccfg' "${grove_version}-${BUILD_NUMBER}.${PACKAGE_OS_VERSION}" "${DEB_ARCH}" 'Grove Traffic Control config generator' '' "${root}"
}

build_tomcat_deb() {
	ensure_cmd curl curl
	ensure_cmd tar tar

	# shellcheck disable=SC1091
	source "${TC_DIR}/.env"
	if [[ -z "${TOMCAT_VERSION:-}" ]]; then
		echo 'TOMCAT_VERSION missing in .env' >&2
		exit 1
	fi
	export TOMCAT_VERSION

	local work
	work="$(mktemp -d)"
	local archive="${work}/apache-tomcat-${TOMCAT_VERSION}.tar.gz"
	curl -fsSL -o "${archive}" "https://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_VERSION%%.*}/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz"

	local stage
	stage="$(mktemp -d)"
	local root="${stage}/root"
	mkdir -p "${root}/opt"
	tar -xzf "${archive}" -C "${root}/opt"
	mv "${root}/opt/apache-tomcat-${TOMCAT_VERSION}" "${root}/opt/tomcat"
	rm -rf "${root}/opt/tomcat/webapps"/*
	rm -f "${root}/opt/tomcat/bin"/*.bat
	mkdir -p "${root}/var/log/tomcat"
	rm -rf "${root}/opt/tomcat/logs"
	ln -s /var/log/tomcat "${root}/opt/tomcat/logs"

	create_deb 'tomcat' "${TOMCAT_VERSION}-1" 'all' 'Apache Tomcat runtime for Traffic Router' 'default-jre-headless' "${root}"
}

build_traffic_router_deb() {
	ensure_cmd mvn maven
	ensure_cmd rsync rsync
	ensure_cmd javac default-jdk-headless

	build_tomcat_deb

	local tr_dir="${TC_DIR}/traffic_router"
	(
		cd "${tr_dir}"
		# Install reactor artifacts to the local Maven repo so the follow-up dependency
		# copy in core does not attempt to resolve sibling modules from remote repos.
		mvn -B -Dmaven.test.skip=true -pl shared,connector,configuration,geolocation,core -am clean install
		(
			cd core
			mvn -B -Dmaven.test.skip=true dependency:copy-dependencies -DincludeScope=runtime -DoutputDirectory=target/dependency
		)
	)

	local stage
	stage="$(mktemp -d)"
	local root="${stage}/root"
	mkdir -p "${root}/opt/traffic_router/conf" "${root}/opt/traffic_router/lib" "${root}/opt/traffic_router/webapps" "${root}/opt/traffic_router/var" "${root}/opt/traffic_router/temp" "${root}/opt/traffic_router/work" "${root}/opt/traffic_router/db" "${root}/var/log/traffic_router" "${root}/lib/systemd/system" "${root}/etc/logrotate.d"

	rsync -a "${tr_dir}/core/src/main/conf/" "${root}/opt/traffic_router/conf/"
	install -m 0644 "${tr_dir}/core/target/ROOT.war" "${root}/opt/traffic_router/webapps/ROOT.war"

	shopt -s nullglob
	local jars=(
		"${tr_dir}/core/target/dependency"/*.jar
	)
	for module in connector shared configuration geolocation; do
		for jar in "${tr_dir}/${module}/target"/*.jar; do
			[[ "${jar}" == *-sources.jar || "${jar}" == *-javadoc.jar ]] && continue
			jars+=("${jar}")
		done
	done
	for jar in "${jars[@]}"; do
		install -m 0644 "${jar}" "${root}/opt/traffic_router/lib/$(basename "${jar}")"
	done

	for f in "${tr_dir}/core/src/main/lib/systemd/system"/*; do
		install -m 0644 "${f}" "${root}/lib/systemd/system/$(basename "${f}")"
	done
	for f in "${tr_dir}/core/src/main/lib/logrotate"/*; do
		install -m 0644 "${f}" "${root}/etc/logrotate.d/$(basename "${f}")"
	done
	shopt -u nullglob

	ln -s /var/log/traffic_router "${root}/opt/traffic_router/var/log"

	create_deb 'traffic_router' "${DEFAULT_DEB_VERSION}" 'all' 'Traffic Router' 'tomcat, default-jre-headless, libapr1, libtcnative-1' "${root}"
}

case "${ATC_COMPONENT}" in
	cache-config)
		build_cache_config_deb
		;;
	tc-health-client)
		build_tc_health_client_deb
		;;
	traffic_monitor)
		build_traffic_monitor_deb
		;;
	traffic_ops)
		build_traffic_ops_deb
		;;
	traffic_portal)
		build_traffic_portal_deb
		;;
	traffic_portal_v2)
		build_traffic_portal_v2_deb
		;;
	traffic_router)
		build_traffic_router_deb
		;;
	traffic_stats)
		build_traffic_stats_deb
		;;
	grove)
		build_grove_deb
		;;
	grovetccfg)
		build_grovetccfg_deb
		;;
	*)
		echo "Unsupported ATC_COMPONENT '${ATC_COMPONENT}'" >&2
		exit 1
		;;
esac

shopt -s nullglob
deb_files=("${DIST_DIR}"/*.deb)
if (( ${#deb_files[@]} == 0 )); then
	echo "No Debian packages were created for ${ATC_COMPONENT}" >&2
	exit 1
fi
