# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

############################################################
# Dockerfile to build Traffic Ops DB admin test environment
# Ubuntu + Debian package
############################################################

FROM ubuntu:24.04
ARG POSTGRES_VERSION
ENV POSTGRES_VERSION=$POSTGRES_VERSION

RUN apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
		ca-certificates \
		cpanminus \
		expat1-dev \
		genisoimage \
		git \
		golang-go \
		libcap2 \
		libcurl4-openssl-dev \
		libdbd-pg-perl \
		libdbi-perl \
		libdigest-sha-perl \
		libexpat1-dev \
		libicu-dev \
		libidn2-dev \
		libjson-perl \
		libpcap-dev \
		libssl-dev \
		libterm-readkey-perl \
		libwww-curl-perl \
		libwww-perl \
		openssl \
		perl \
		postgresql-client \
		python3 && \
	rm -rf /var/lib/apt/lists/*

# Override TRAFFIC_OPS_DEB arg to use a different one using --build-arg TRAFFIC_OPS_DEB=... .
ARG TRAFFIC_OPS_DEB=traffic_ops.deb
ADD $TRAFFIC_OPS_DEB /
RUN dpkg -i --force-depends "$(basename "$TRAFFIC_OPS_DEB")" && \
	rm "$(basename "$TRAFFIC_OPS_DEB")"

WORKDIR /opt/traffic_ops/app

ADD run-tvdb-test.sh \
    db-config.sh \
    reencrypt-config.sh \
    data/sslkey.dat \
    data/dnssec.dat \
    data/urisigningkey.dat \
    data/urlsigkey.dat \
    aes.key \
    new-aes.key \
    /

COPY initdb.d/ /db_dumps/

CMD /run-tvdb-test.sh
